// Generated by CoffeeScript 1.3.3
(function() {
  var DEBUG, app, checkQuery, elementtree, express, http;

  http = require('http');

  elementtree = require('elementtree');

  express = require('express');

  app = express();

  DEBUG = true;

  /*
  # Check RSS petition and load its parser
  */


  checkQuery = function(rssUrl) {
    /*
    	http.get API_URL, (response) ->
    		data = ''
    		response.on 'data', (chunk) ->
    			data += chunk
    		response.on 'end', ->
    			tree = elementtree.parse data
    			result = ##
    	.on 'error', (error) ->
    		console.log error.message
    */

  };

  app.get("/", function(request, response) {
    return response.end('Decent home!');
  });

  app.all("*", function(request, response) {
    if (request.url !== '/') {
      response.send(request.url.substr(1));
    }
    return response.end();
  });

  app.listen(process.env.VCAP_APP_PORT || 3000);

}).call(this);
