// Generated by CoffeeScript 1.3.3
var elementtree, http, nyaaeu, parser,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

http = require('http');

elementtree = require('elementtree');

parser = (function() {

  function parser() {}

  parser.tree = null;

  parser.prototype.get = function(_url) {
    if (_url == null) {
      _url = "";
    }
    return http.get("http://" + _url, function(response) {
      var data;
      data = '';
      response.on('data', function(chunk) {
        return data += chunk;
      });
      return response.on('end', function() {
        return this.tree = elementtree.parse(data);
      });
    }).on('error', function(error) {
      return console.log(error.message);
    });
  };

  parser.prototype.foo = function() {
    return console.log("DIS IS DEFAULT");
  };

  return parser;

})();

nyaaeu = (function(_super) {

  __extends(nyaaeu, _super);

  function nyaaeu() {
    return nyaaeu.__super__.constructor.apply(this, arguments);
  }

  nyaaeu.prototype.foo = function() {
    return console.log("DIS IS NYAAEU");
  };

  return nyaaeu;

})(parser);

module.exports = {
  'default': parser,
  'nyaaeu': nyaaeu
};
